import React, { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import Img from './Img.tsx'

const ink = 'var(--timeline-colors-gray-600)'
const cream = 'var(--timeline-colors-gray-50)'
const sand = 'var(--timeline-colors-gray-100)'
const coral = 'var(--timeline-colors-red-300)'

function Header() {
  const location = useLocation()
  const [open, setOpen] = useState(false)
  const links = [['Shop', '/shop'], ['Science', '/science'], ['About', '/about'], ['FAQ', '/faq']]

  return <header style={{ position: 'sticky', top: 0, zIndex: 10, background: cream, borderBottom: '1px solid var(--timeline-colors-blackAlpha-200)' }}>
    <div className="acement-header-inner" style={{ maxWidth: 1240, margin: '0 auto', minHeight: 78, padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20 }}>
      <Link className="acement-logo" to="/" style={{ color: ink, fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-2xl-serif)', textDecoration: 'none', letterSpacing: '-0.06em' }}>ace—ment</Link>
      <button className="acement-menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation" style={{ display: 'none' }}>Menu</button>
      <nav className={`acement-nav${open ? ' encement-nav-open' : ''}`} aria-label="Main navigation" style={{ display: 'flex', alignItems: 'center', gap: 26, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
        {links.map(([label, href]) => <Link key={href} to={href} style={{ color: location.pathname === href ? coral : ink, fontFamily: 'var(--timeline-fonts-sans)', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.08em', textDecoration: 'none', textTransform: 'uppercase' }}>{label}</Link>)}
        <Link to="/products/mitopure-softgels-vegan" style={{ background: ink, color: cream, padding: '12px 16px', borderRadius: 'var(--timeline-radii-base)', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.08em', textDecoration: 'none', textTransform: 'uppercase' }}>Shop softgels</Link>
      </nav>
    </div>
  </header>
}

const ButtonLink = ({ to, children, quiet = false }: { to: string, children: React.ReactNode, quiet?: boolean }) => <Link to={to} style={{ display: 'inline-block', textDecoration: 'none', background: quiet ? 'transparent' : ink, color: quiet ? ink : cream, padding: quiet ? '0 0 4px' : '15px 22px', borderBottom: quiet ? `1px solid ${ink}` : undefined, borderRadius: quiet ? 0 : 'var(--timeline-radii-base)', fontFamily: 'var(--timeline-fonts-sans)', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>{children}</Link>

const SectionIntro = ({ eyebrow, title, children }: { eyebrow: string, title: string, children?: React.ReactNode }) => <div style={{ maxWidth: 800, marginBottom: 48 }}>
  <p style={{ color: coral, margin: '0 0 14px', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.12em', textTransform: 'uppercase' }}>{eyebrow}</p>
  <h1 style={{ color: ink, margin: 0, fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-4xl)', lineHeight: 1.03, letterSpacing: '-0.045em' }}>{title}</h1>
  {children && <p style={{ color: 'var(--timeline-colors-blackAlpha-700)', fontSize: 'var(--timeline-fontSizes-md)', lineHeight: 1.5, margin: '20px 0 0', maxWidth: 640 }}>{children}</p>}
</div>

function ShopPage() {
  return <PageShell><SectionIntro eyebrow="Supplements" title="Better aging, from the cellular level.">Clinically studied daily nutrition created to support energy, muscle strength, and healthy aging.</SectionIntro>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
      <ProductTile title="Mitopure Softgels" description="The simplest daily dose of Mitopure." imageId="2" badge="Bestseller" />
      <ProductTile title="Mitopure Gummies" description="A strawberry-flavored ritual for cellular renewal." imageId="0" badge="Sugar free" />
      <article style={{ background: ink, color: cream, borderRadius: 'var(--timeline-radii-lg)', padding: 32, minHeight: 360, display: 'flex', flexDirection: 'column', justifyContent: 'flex-end' }}><p style={{ fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.1em', textTransform: 'uppercase', margin: 0 }}>Not sure where to start?</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-2xl-serif)', fontWeight: 400, margin: '16px 0' }}>Find your daily formula.</h2><ButtonLink to="/products/mitopure-softgels-vegan">Explore softgels</ButtonLink></article>
    </div>
  </PageShell>
}

function ProductTile({ title, description, imageId, badge }: { title: string, description: string, imageId: string, badge: string }) {
  return <article style={{ background: sand, borderRadius: 'var(--timeline-radii-lg)', overflow: 'hidden' }}><div style={{ height: 310, padding: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}><span style={{ position: 'absolute', top: 18, left: 18, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.08em', textTransform: 'uppercase', background: cream, padding: '7px 9px', borderRadius: 'var(--timeline-radii-base)' }}>{badge}</span><div style={{ maxWidth: 220 }}><Img id={imageId} /></div></div><div style={{ background: cream, padding: 22 }}><p style={{ margin: '0 0 8px', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.09em' }}>4.8 / 5.0</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-xl)', margin: '0 0 8px' }}>{title}</h2><p style={{ color: 'var(--timeline-colors-blackAlpha-700)', margin: '0 0 18px' }}>{description}</p><ButtonLink to="/products/mitopure-softgels-vegan" quiet>View product</ButtonLink></div></article>
}

function ProductPage() {
  const [quantity, setQuantity] = useState(1)
  const [subscription, setSubscription] = useState(true)
  const [added, setAdded] = useState(false)
  return <PageShell><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 56, alignItems: 'start' }}>
    <div style={{ background: sand, borderRadius: 'var(--timeline-radii-xl)', minHeight: 540, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 32 }}><div style={{ maxWidth: 390 }}><Img id="2" /></div></div>
    <div><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.1em', textTransform: 'uppercase', margin: '10px 0' }}>Best seller</p><h1 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-4xl)', letterSpacing: '-0.05em', margin: '0 0 14px' }}>Mitopure Softgels</h1><p style={{ fontSize: 'var(--timeline-fontSizes-sm)', margin: '0 0 18px' }}>4.5 / 5.0 <span style={{ color: 'var(--timeline-colors-blackAlpha-600)' }}>from 4,539 reviews</span></p><p style={{ fontSize: 'var(--timeline-fontSizes-md)', lineHeight: 1.5, color: 'var(--timeline-colors-blackAlpha-700)' }}>A precise daily dose of Mitopure, our clinically studied form of Urolithin A.</p>
      <p style={{ fontSize: 'var(--timeline-fontSizes-xl)', margin: '28px 0' }}>$85.00 <span style={{ fontSize: 'var(--timeline-fontSizes-xs)', color: 'var(--timeline-colors-blackAlpha-600)' }}>per month</span></p>
      <div style={{ display: 'grid', gap: 10, marginBottom: 18 }}><button onClick={() => setSubscription(true)} style={{ cursor: 'pointer', border: subscription ? `2px solid ${ink}` : '1px solid var(--timeline-colors-blackAlpha-250)', background: subscription ? sand : cream, borderRadius: 'var(--timeline-radii-base)', textAlign: 'left', padding: 16, color: ink, font: 'inherit' }}><strong>Subscribe & save 10%</strong><br /><span style={{ fontSize: 'var(--timeline-fontSizes-xs)' }}>Delivered every 30 days. Pause or cancel anytime.</span></button><button onClick={() => setSubscription(false)} style={{ cursor: 'pointer', border: !subscription ? `2px solid ${ink}` : '1px solid var(--timeline-colors-blackAlpha-250)', background: !subscription ? sand : cream, borderRadius: 'var(--timeline-radii-base)', textAlign: 'left', padding: 16, color: ink, font: 'inherit' }}><strong>One-time purchase</strong><br /><span style={{ fontSize: 'var(--timeline-fontSizes-xs)' }}>Try it at your own pace.</span></button></div>
      <div style={{ display: 'flex', gap: 12 }}><div style={{ display: 'flex', border: '1px solid var(--timeline-colors-blackAlpha-250)', borderRadius: 'var(--timeline-radii-base)' }}><button onClick={() => setQuantity(Math.max(1, quantity - 1))} style={{ border: 0, background: 'transparent', padding: '0 15px', cursor: 'pointer', fontSize: 20 }}>-</button><span style={{ minWidth: 30, alignSelf: 'center', textAlign: 'center' }}>{quantity}</span><button onClick={() => setQuantity(quantity + 1)} style={{ border: 0, background: 'transparent', padding: '0 15px', cursor: 'pointer', fontSize: 20 }}>+</button></div><button onClick={() => setAdded(true)} style={{ flex: 1, cursor: 'pointer', border: 0, background: added ? coral : ink, color: cream, borderRadius: 'var(--timeline-radii-base)', fontFamily: 'var(--timeline-fonts-sans)', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.09em', textTransform: 'uppercase' }}>{added ? 'Added to cart' : 'Add to cart'}</button></div>
    </div></div>
    <section style={{ marginTop: 96, borderTop: '1px solid var(--timeline-colors-blackAlpha-200)', paddingTop: 48 }}><SectionIntro eyebrow="How it works" title="Support your cells from within.">Mitopure is a pure, bioavailable form of Urolithin A, designed to support mitochondrial renewal as you age.</SectionIntro><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 20 }}>{[['Daily ritual', 'Two softgels daily, with or without food.'], ['Clinically studied', 'Built on decades of research and human clinical trials.'], ['Vegan formula', 'Made without unnecessary fillers or compromises.']].map(([title, copy], index) => <div key={title} style={{ padding: 24, background: sand, borderRadius: 'var(--timeline-radii-lg)' }}><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)' }}>0{index + 1}</p><h3 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-xl)', fontWeight: 400 }}>{title}</h3><p style={{ color: 'var(--timeline-colors-blackAlpha-700)', lineHeight: 1.5 }}>{copy}</p></div>)}</div></section>
  </PageShell>
}

function SciencePage() { return <PageShell><SectionIntro eyebrow="Our science" title="The biology of better aging.">We focus on the cellular processes that help you stay stronger, longer.</SectionIntro><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(290px, 1fr))', gap: 24 }}><ScienceCard number="18" title="Years of research" copy="A research platform developed alongside leading scientists in longevity and mitochondrial biology." /><ScienceCard number="25" title="Human clinical trials" copy="Rigorous research designed to understand the impact of Urolithin A across life stages." /><ScienceCard number="500+" title="Published studies" copy="A growing body of work examining the biology behind mitochondrial renewal." /></div><section style={{ marginTop: 80, background: ink, color: cream, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(32px, 7vw, 80px)' }}><p style={{ color: '#e1a39c', letterSpacing: '0.1em', fontSize: 'var(--timeline-fontSizes-2xs-mono)', textTransform: 'uppercase' }}>Mitophagy</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-3xl)', maxWidth: 740, margin: '0 0 20px' }}>A natural cellular renewal process, awakened.</h2><p style={{ maxWidth: 600, lineHeight: 1.6, fontSize: 'var(--timeline-fontSizes-md)', color: 'rgba(255,255,255,0.75)' }}>As we age, our cells become less efficient at recycling damaged mitochondria. Mitopure supports the body’s natural renewal pathways.</p></section></PageShell> }
function ScienceCard({ number, title, copy }: { number: string, title: string, copy: string }) { return <article style={{ borderTop: `2px solid ${coral}`, padding: '24px 0' }}><p style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-4xl)', margin: 0 }}>{number}</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-xl)' }}>{title}</h2><p style={{ lineHeight: 1.5, color: 'var(--timeline-colors-blackAlpha-700)' }}>{copy}</p></article> }

function AboutPage() { return <PageShell><SectionIntro eyebrow="About Acement" title="We make longevity feel personal.">We believe the best science should make a difference in your real life, not just on a lab report.</SectionIntro><div style={{ background: sand, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(30px, 6vw, 72px)', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 36 }}><div><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Our standard</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-2xl-serif)' }}>Evidence first. Always.</h2></div><p style={{ lineHeight: 1.6, fontSize: 'var(--timeline-fontSizes-md)' }}>Our formulas start with meaningful research, transparent ingredients, and a simple promise: every product should earn a place in your routine.</p></div><div style={{ marginTop: 72, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 24 }}>{[['01', 'Thoughtful by design'], ['02', 'Clinically grounded'], ['03', 'Made for consistency']].map(([number, title]) => <div key={number}><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)' }}>{number}</p><h3 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-xl)' }}>{title}</h3></div>)}</div></PageShell> }

function FaqPage() { const [active, setActive] = useState<number | null>(0); const faqs = [['What is Mitopure?', 'Mitopure is a highly pure form of Urolithin A, a compound researched for its role in supporting mitochondrial renewal.'], ['How do I take it?', 'Take two softgels daily, consistently, with or without food.'], ['When will I notice a difference?', 'Individual experiences vary. Consistency matters, and many people make it part of a long-term wellness routine.'], ['Can I pause a subscription?', 'Yes. Subscription preferences can be managed at any time.']]; return <PageShell><SectionIntro eyebrow="Support" title="Questions, answered.">Everything you need to know about Acement and our formulas.</SectionIntro><div style={{ borderTop: '1px solid var(--timeline-colors-blackAlpha-200)' }}>{faqs.map(([question, answer], index) => <div key={question} style={{ borderBottom: '1px solid var(--timeline-colors-blackAlpha-200)' }}><button onClick={() => setActive(active === index ? null : index)} style={{ width: '100%', display: 'flex', justifyContent: 'space-between', textAlign: 'left', padding: '22px 0', cursor: 'pointer', border: 0, background: 'transparent', color: ink, font: 'inherit', fontSize: 'var(--timeline-fontSizes-md)' }}><span>{question}</span><span>{active === index ? '−' : '+'}</span></button>{active === index && <p style={{ maxWidth: 700, margin: '0 0 24px', lineHeight: 1.6, color: 'var(--timeline-colors-blackAlpha-700)' }}>{answer}</p>}</div>)}</div></PageShell> }

function PageShell({ children }: { children: React.ReactNode }) { return <body className="chakra-ui-light" style={{ margin: 0, background: cream, color: ink, fontFamily: 'var(--timeline-fonts-sans)' }}><Header /><main style={{ maxWidth: 1240, margin: '0 auto', padding: 'clamp(52px, 8vw, 112px) 24px' }}>{children}</main><footer style={{ borderTop: '1px solid var(--timeline-colors-blackAlpha-200)', padding: '32px 24px', color: 'var(--timeline-colors-blackAlpha-700)' }}><div style={{ maxWidth: 1240, margin: '0 auto', display: 'flex', justifyContent: 'space-between', gap: 24, flexWrap: 'wrap' }}><span>© 2026 Acement</span><Link to="/contact" style={{ color: ink }}>Contact</Link></div></footer></body> }

function ContactPage() { return <PageShell><SectionIntro eyebrow="Contact" title="We’re here to help.">For product questions, order support, or wholesale inquiries, send us a note.</SectionIntro><a href="mailto:hello@acement.com" style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-3xl)', color: ink }}>hello@acement.com</a></PageShell> }

export { ShopPage, ProductPage, SciencePage, AboutPage, FaqPage, ContactPage }
