import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { ButtonLink, PageShell, SectionIntro } from './AcementSite.tsx'

const ink = 'var(--timeline-colors-gray-600)'
const cream = 'var(--timeline-colors-gray-50)'
const sand = 'var(--timeline-colors-gray-100)'
const coral = 'var(--timeline-colors-red-300)'
const card = { background: cream, border: '1px solid var(--timeline-colors-blackAlpha-200)', borderRadius: 'var(--timeline-radii-lg)', padding: 24 }

function ReviewsPage() {
  const reviews = [['Stergios P.', 'Mitopure Softgels', 'Encouraging initial observations', 'Verified buyer · Age 60–69', 'My first months of consistent use have felt positive. I appreciate the science-first approach and have made it part of my daily routine.'], ['Craig S.', 'Mitopure Gummies', 'More energy for training', 'Verified buyer', 'I find it supports my recovery and energy when I am training consistently.'], ['Louis R.', 'Mitopure Gummies', 'Worth making part of my routine', 'Verified buyer · Age 70+', 'I have made it a consistent part of my morning routine and value the focus on long-term health.']]
  return <PageShell><SectionIntro eyebrow="Community" title="Reviews from verified buyers.">Experiences shared by people making cellular health part of their everyday routine.</SectionIntro><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 16, padding: 28, background: sand, borderRadius: 'var(--timeline-radii-lg)' }}><div><strong style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-3xl)', fontWeight: 400 }}>4.7 / 5</strong><p>Based on 13,478 reviews</p></div>{[['78%', '5 stars'], ['14%', '4 stars'], ['95%', 'Would recommend']].map(([n, label]) => <div key={label}><strong style={{ fontSize: 'var(--timeline-fontSizes-xl)' }}>{n}</strong><p>{label}</p></div>)}</section><div style={{ marginTop: 24, display: 'flex', gap: 10, flexWrap: 'wrap' }}>{['All products', 'Softgels', 'Gummies', 'Most recent', 'Highest rated'].map(filter => <button key={filter} style={{ border: '1px solid var(--timeline-colors-blackAlpha-250)', background: cream, borderRadius: 30, padding: '9px 14px', color: ink }}>{filter}</button>)}</div><section style={{ marginTop: 34, display: 'grid', gap: 14 }}>{reviews.map(([name, product, title, detail, copy]) => <article key={name} style={card}><p style={{ color: coral, margin: 0, letterSpacing: '0.08em' }}>★★★★★</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-xl)' }}>{title}</h2><p style={{ lineHeight: 1.55 }}>{copy}</p><p style={{ marginBottom: 0, color: 'var(--timeline-colors-blackAlpha-700)' }}><strong>{name}</strong> · {detail}<br />Reviewed {product}</p></article>)}</section></PageShell>
}

function TestimonialsPage() {
  const people = [['Eric Verdin, MD', 'CEO, Buck Institute for Research on Aging', 'Mitochondrial decline is a key hallmark of aging, and supporting mitochondrial quality is one of the most promising areas in healthy-aging research.'], ['Dr. Mark Hyman, MD', 'Functional Medicine Physician', 'This is a daily ritual I value for supporting healthy aging and staying active over time.'], ['Tia-Clair Toomey', 'Professional athlete', 'A consistent training plan begins with a consistent recovery routine.'], ['Thomas DeLauer', 'Nutrition and performance coach', 'I look for products built with clear, science-first standards.']]
  return <PageShell><SectionIntro eyebrow="Recommended by" title="Scientists, doctors, and longevity experts.">Conversations with people who care deeply about healthy aging, performance, and the science behind daily habits.</SectionIntro><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(270px, 1fr))', gap: 18 }}>{people.map(([name, role, quote]) => <article key={name} style={{ ...card, minHeight: 270, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}><p style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-xl)', lineHeight: 1.3, margin: 0 }}>“{quote}”</p><div><h2 style={{ margin: '22px 0 4px', fontSize: 'var(--timeline-fontSizes-sm)' }}>{name}</h2><p style={{ margin: 0, color: 'var(--timeline-colors-blackAlpha-700)' }}>{role}</p></div></article>)}</div><section style={{ marginTop: 80, background: ink, color: cream, padding: 'clamp(30px, 6vw, 72px)', borderRadius: 'var(--timeline-radii-xl)' }}><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-3xl)', marginTop: 0 }}>Discover the daily formula behind the conversation.</h2><ButtonLink to="/shop">Shop supplements</ButtonLink></section></PageShell>
}

function BlogPage() {
  const posts = [['News', 'Timeline’s Mitopure technology is launching globally', 'An update on the growing conversation around cellular health and longevity science.'], ['Nutrition', 'Why are mitochondria important?', 'A practical introduction to the engines that power every cell in the body.'], ['Nutrition', 'How to select an effective Urolithin A supplement', 'What to look for when evaluating purity, research, and daily dosage.'], ['Nutrition', 'Age-related muscle loss: how to stay strong', 'The habits and science that support strength across the decades.'], ['Studies', 'What human clinical trials tell us about Urolithin A', 'How researchers study mitochondrial health and performance.'], ['Lifestyle', 'Building a longevity routine that lasts', 'Simple, sustainable ways to focus on healthspan.']]
  return <PageShell><SectionIntro eyebrow="Journal" title="The science of living well, longer.">Research, expert perspectives, and practical ideas for your daily healthspan routine.</SectionIntro><nav style={{ display: 'flex', flexWrap: 'wrap', gap: 16, marginBottom: 34 }}>{['All', 'News', 'Nutrition', 'Science', 'Lifestyle'].map(item => <button key={item} style={{ border: 0, padding: 0, background: 'transparent', color: item === 'All' ? coral : ink, font: 'inherit' }}>{item}</button>)}</nav><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(270px, 1fr))', gap: 18 }}>{posts.map(([category, title, excerpt], index) => <article key={title} style={card}><div style={{ height: 150, background: index % 2 ? sand : ink, borderRadius: 'var(--timeline-radii-base)', marginBottom: 20 }} /><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '0.09em', textTransform: 'uppercase' }}>{category} · 6 min read</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-xl)', fontWeight: 400 }}>{title}</h2><p style={{ lineHeight: 1.5, color: 'var(--timeline-colors-blackAlpha-700)' }}>{excerpt}</p><a href="#" style={{ color: ink }}>Read article</a></article>)}</div></PageShell>
}

function DetailedFaqPage() { const [open, setOpen] = useState<number | null>(0); const items = [['About Acement', 'What is Acement?', 'Acement develops daily longevity formulas grounded in research into mitochondrial and cellular health.'], ['About Acement', 'What makes your formulas different?', 'We prioritize transparent dosing, quality standards, and research-backed ingredients.'], ['Formula & science', 'What is Urolithin A?', 'Urolithin A is a naturally occurring compound studied for its role in mitochondrial renewal processes.'], ['Formula & science', 'Can I get enough from diet alone?', 'Dietary conversion differs substantially from person to person, which is why precise supplemental forms exist.'], ['Usage & dosage', 'How should I take Softgels?', 'Take two softgels daily. They can be taken with or without food.'], ['Usage & dosage', 'When should I expect results?', 'Experiences vary. Consistency over several months is generally the most meaningful way to assess a daily wellness routine.'], ['Safety & quality', 'Is the formula suitable for daily use?', 'Follow label directions and consult a qualified clinician if you are pregnant, nursing, taking medication, or have a medical condition.'], ['Safety & quality', 'Is it allergen friendly?', 'Review the product label for the current ingredient and allergen information.'], ['Orders & subscriptions', 'Can I change or pause a subscription?', 'Yes. Subscription preferences can be managed before the next order is processed.'], ['Orders & subscriptions', 'How can I contact support?', 'Email hello@acement.com with your order number and question.']]; return <PageShell><SectionIntro eyebrow="Support" title="Questions, answered.">Browse product, science, safety, and order information.</SectionIntro><div style={{ display: 'grid', gap: 22 }}>{items.map(([category, question, answer], index) => <section key={question}><p style={{ color: coral, margin: '0 0 8px', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.08em', textTransform: 'uppercase' }}>{category}</p><div style={{ borderTop: '1px solid var(--timeline-colors-blackAlpha-200)', borderBottom: '1px solid var(--timeline-colors-blackAlpha-200)' }}><button onClick={() => setOpen(open === index ? null : index)} style={{ width: '100%', display: 'flex', justifyContent: 'space-between', textAlign: 'left', border: 0, background: 'transparent', padding: '18px 0', color: ink, font: 'inherit', fontSize: 'var(--timeline-fontSizes-md)' }}><span>{question}</span><span>{open === index ? '−' : '+'}</span></button>{open === index && <p style={{ margin: '0 0 20px', maxWidth: 780, lineHeight: 1.6, color: 'var(--timeline-colors-blackAlpha-700)' }}>{answer}</p>}</div></section>)}</div></PageShell> }

function LegalPage({ privacy = false }: { privacy?: boolean }) { const title = privacy ? 'Privacy policy' : 'Terms and conditions'; const sections = privacy ? [['Information we collect', 'We collect information you provide when placing an order, subscribing, contacting us, or using the site.'], ['How we use information', 'We use information to fulfill orders, provide support, improve the site, and send marketing where permitted.'], ['Your choices', 'You may request access, correction, deletion, or opt out of marketing communications.']] : [['Using this site', 'Use this site lawfully and do not interfere with its security, operation, or content.'], ['Products and orders', 'Product availability, pricing, shipping, returns, and subscriptions are subject to the information shown at checkout.'], ['Health information', 'Product information is not medical advice. Consult a qualified healthcare professional before beginning a new supplement routine.']]; return <PageShell><SectionIntro eyebrow="Legal" title={title}>Last updated: August 28, 2026. This is a website template and must be reviewed with Acement’s actual business, order, payment, and data-processing details before launch.</SectionIntro><div style={{ maxWidth: 820 }}>{sections.map(([heading, copy]) => <section key={heading} style={{ padding: '26px 0', borderTop: '1px solid var(--timeline-colors-blackAlpha-200)' }}><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-xl)', fontWeight: 400 }}>{heading}</h2><p style={{ lineHeight: 1.6, color: 'var(--timeline-colors-blackAlpha-700)' }}>{copy}</p></section>)}<p style={{ paddingTop: 26 }}>Contact: <a href="mailto:hello@acement.com" style={{ color: ink }}>hello@acement.com</a></p></div></PageShell> }

export { ReviewsPage, TestimonialsPage, BlogPage, DetailedFaqPage, LegalPage }
