import React, { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { PageShell, SectionIntro } from './AcementSite.tsx'

type Post = { slug: string, category: string, date: string, minutes: string, title: string, excerpt: string, body: string[] }

// Add a new object here to publish another article. The index and article route update automatically.
const posts: Post[] = [
  { slug: 'why-mitochondria-matter', category: 'Nutrition', date: 'Aug 13, 2026', minutes: '6 min read', title: 'Why mitochondria matter for healthy aging', excerpt: 'A practical guide to the cellular engines that support energy, strength, and resilience.', body: ['Mitochondria help cells turn nutrients into usable energy. They are active in nearly every system of the body, from muscle and brain function to recovery after activity.', 'As we age, mitochondrial quality and efficiency can change. Supporting healthy daily habits such as movement, sleep, nutrition, and consistency is an important foundation for long-term health.', 'Science is increasingly focused on the processes that help cells recycle damaged mitochondrial material and maintain a healthier cellular environment.'] },
  { slug: 'building-a-longevity-routine', category: 'Lifestyle', date: 'Jul 29, 2026', minutes: '5 min read', title: 'How to build a longevity routine that lasts', excerpt: 'The habits that matter are the ones you can repeat, not the ones that feel perfect for a week.', body: ['A useful longevity routine begins with a realistic baseline: consistent sleep, daily movement, a nutrient-dense diet, and a small number of habits that fit your schedule.', 'Start with one change at a time. Track how it feels, refine it, and give it enough time to become automatic before adding another commitment.', 'The goal is not optimization at all costs. It is a routine that helps you stay active, capable, and engaged for the long term.'] },
  { slug: 'choosing-urolithin-a', category: 'Science', date: 'Jul 10, 2026', minutes: '7 min read', title: 'What to look for in a Urolithin A supplement', excerpt: 'Purity, dosage, evidence, and quality standards are useful starting points when evaluating a daily formula.', body: ['When comparing supplements, begin with transparency. Look for a clearly stated active ingredient and dose, accessible quality information, and a brand that explains the research behind its product.', 'Human clinical evidence is different from preliminary findings. Ask what population was studied, how long the study lasted, and what outcomes were measured.', 'A supplement is most useful when it is appropriate for your goals and fits a routine you can sustain. Discuss questions with a qualified healthcare professional.'] },
  { slug: 'staying-strong-through-the-decades', category: 'Nutrition', date: 'Jun 24, 2026', minutes: '8 min read', title: 'Staying strong through the decades', excerpt: 'Strength is built from small, repeated signals: movement, protein, recovery, and time.', body: ['Muscle is central to mobility, metabolic health, and independence. The best strategy is usually a straightforward one: move regularly, include resistance work when appropriate, and prioritize recovery.', 'Protein-rich meals and enough total energy help support training adaptations. Sleep is equally important, since it is when much of the body’s repair work takes place.', 'Every decade benefits from an approach that respects current fitness, experience, and medical needs.'] },
]

function BlogIndexPage() {
  const [category, setCategory] = useState('All')
  const categories = ['All', ...Array.from(new Set(posts.map(post => post.category)))]
  const shown = category === 'All' ? posts : posts.filter(post => post.category === category)
  return <PageShell><SectionIntro eyebrow="Journal" title="The science of living well, longer.">Research, expert perspectives, and practical ideas for a considered healthspan routine.</SectionIntro><div style={{ display: 'flex', flexWrap: 'wrap', gap: 18, marginBottom: 36 }}>{categories.map(item => <button onClick={() => setCategory(item)} key={item} style={{ cursor: 'pointer', border: 0, padding: '0 0 5px', background: 'transparent', borderBottom: category === item ? '1px solid var(--timeline-colors-gray-600)' : '1px solid transparent', color: category === item ? 'var(--timeline-colors-red-300)' : 'var(--timeline-colors-gray-600)', font: 'inherit' }}>{item}</button>)}</div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(270px, 1fr))', gap: 20 }}>{shown.map((post, index) => <article key={post.slug} style={{ border: '1px solid var(--timeline-colors-blackAlpha-200)', borderRadius: 'var(--timeline-radii-lg)', overflow: 'hidden', background: 'var(--timeline-colors-gray-50)' }}><div style={{ height: 160, background: index % 2 ? 'var(--timeline-colors-gray-100)' : 'var(--timeline-colors-gray-600)' }} /><div style={{ padding: 24 }}><p style={{ color: 'var(--timeline-colors-red-300)', margin: 0, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.08em', textTransform: 'uppercase' }}>{post.category} · {post.date}</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-xl)', fontWeight: 400 }}>{post.title}</h2><p style={{ lineHeight: 1.5, color: 'var(--timeline-colors-blackAlpha-700)' }}>{post.excerpt}</p><Link to={`/blog/${post.slug}`} style={{ color: 'var(--timeline-colors-gray-600)' }}>Read article</Link></div></article>)}</div></PageShell>
}

function BlogPostPage() { const { slug } = useParams(); const post = posts.find(item => item.slug === slug); if (!post) return <PageShell><SectionIntro eyebrow="Journal" title="Article not found." /><Link to="/blog">Back to journal</Link></PageShell>; return <PageShell><article style={{ maxWidth: 800, margin: '0 auto' }}><p style={{ color: 'var(--timeline-colors-red-300)', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.08em', textTransform: 'uppercase' }}>{post.category} · {post.date} · {post.minutes}</p><h1 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-4xl)', fontWeight: 400, letterSpacing: '-.045em', lineHeight: 1.04 }}>{post.title}</h1><p style={{ fontSize: 'var(--timeline-fontSizes-lg)', lineHeight: 1.5, color: 'var(--timeline-colors-blackAlpha-700)' }}>{post.excerpt}</p><div style={{ height: 300, borderRadius: 'var(--timeline-radii-lg)', background: 'var(--timeline-colors-gray-100)', margin: '36px 0' }} />{post.body.map(paragraph => <p key={paragraph} style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-md-serif)', lineHeight: 1.65 }}>{paragraph}</p>)}<Link to="/blog" style={{ display: 'inline-block', marginTop: 32, color: 'var(--timeline-colors-gray-600)' }}>Back to journal</Link></article></PageShell> }

export { BlogIndexPage, BlogPostPage }
