import React from 'react'
import { Link } from 'react-router-dom'
import Img from './Img.tsx'
import { ButtonLink, PageShell, SectionIntro } from './AcementSite.tsx'

const ink = 'var(--timeline-colors-gray-600)'
const cream = 'var(--timeline-colors-gray-50)'
const sand = 'var(--timeline-colors-gray-100)'
const coral = 'var(--timeline-colors-red-300)'

function FullSciencePage() {
  const outcomes = [['Renewal', '+39%', 'Increases mitochondrial renewal after 16 weeks over placebo.'], ['Energy', '↑', 'Induces a signature of improved mitochondrial function.'], ['Strength', '+12%', 'Increases muscle strength after 16 weeks in clinical research.'], ['Bioavailability', '6x', 'Unlocks more Urolithin A than diet alone.']]
  return <PageShell><SectionIntro eyebrow="Science of Mitopure" title="The supplement that changes how cells age.">Your body is made of trillions of cells. How you feel now and as you age depends on their health.</SectionIntro>
    <section style={{ background: sand, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(32px, 6vw, 72px)' }}><p style={{ maxWidth: 720, fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-2xl-serif)', lineHeight: 1.2, margin: 0 }}>Mitochondria are the batteries that make your cells work. These cellular batteries can become less efficient with age.</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 14, marginTop: 36 }}>{['Insufficient energy supply', 'Production of harmful molecules', 'Reduced cellular health'].map(item => <div key={item} style={{ background: cream, padding: 22, borderRadius: 'var(--timeline-radii-base)' }}>{item}</div>)}</div></section>
    <section style={{ marginTop: 96 }}><SectionIntro eyebrow="Whole-body impact" title="Weak mitochondria affect every system in your body." /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 10 }}>{['Brain', 'Skin', 'Immune system', 'Joints', 'Digestive system', 'Skeletal muscle'].map(item => <div key={item} style={{ minHeight: 112, padding: 18, background: item === 'Skeletal muscle' ? ink : sand, color: item === 'Skeletal muscle' ? cream : ink, borderRadius: 'var(--timeline-radii-lg)', display: 'flex', alignItems: 'flex-end' }}>{item}</div>)}</div></section>
    <section style={{ marginTop: 96 }}><SectionIntro eyebrow="A healthy aging breakthrough" title="Clinically proven to revitalize mitochondria." /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))', gap: 1, background: 'var(--timeline-colors-blackAlpha-200)' }}>{outcomes.map(([name, stat, copy]) => <article key={name} style={{ background: cream, padding: 28, minHeight: 220 }}><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.1em', margin: 0, textTransform: 'uppercase' }}>{name}</p><strong style={{ display: 'block', fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-3xl)', fontWeight: 400, margin: '14px 0' }}>{stat}</strong><p style={{ lineHeight: 1.55, color: 'var(--timeline-colors-blackAlpha-700)' }}>{copy}</p><a href="#study-details" style={{ color: ink }}>See study details</a></article>)}</div></section>
    <section style={{ marginTop: 96, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24, alignItems: 'stretch' }}><div style={{ background: ink, color: cream, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(28px, 5vw, 56px)' }}><p style={{ color: '#e1a39c', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.1em', textTransform: 'uppercase' }}>Did you know?</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-3xl)', fontWeight: 400, lineHeight: 1.08 }}>Only 1 in 3 people can get enough Urolithin A from diet alone.</h2><p style={{ color: 'rgba(255,255,255,.76)', lineHeight: 1.6 }}>Conversion from dietary precursors varies. A precise, researched daily dose provides a consistent approach.</p></div><div id="study-details" style={{ background: sand, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(28px, 5vw, 56px)' }}><p style={{ color: coral, fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.1em', textTransform: 'uppercase' }}>Research details</p><h2 style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-2xl-serif)', fontWeight: 400 }}>Evidence designed for real life.</h2><p style={{ lineHeight: 1.6 }}>Our research framework combines cellular biology, human clinical trials, and ongoing investigation into healthy aging.</p><ButtonLink to="/benefits" quiet>Explore benefits</ButtonLink></div></section>
    <section style={{ marginTop: 96, display: 'grid', gridTemplateColumns: 'minmax(260px, .75fr) 1fr', gap: 36, alignItems: 'center' }}><div style={{ background: sand, borderRadius: 'var(--timeline-radii-xl)', overflow: 'hidden' }}><Img id="23" /></div><blockquote style={{ margin: 0 }}><p style={{ fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-2xl-serif)', lineHeight: 1.25 }}>“A daily, evidence-led approach to mitochondrial health is one of the most promising directions in longevity science.”</p><footer><strong>Dr. Mark Hyman, MD</strong><br /><span style={{ color: 'var(--timeline-colors-blackAlpha-700)' }}>Functional Medicine Physician</span></footer></blockquote></section>
    <section style={{ marginTop: 96 }}><SectionIntro eyebrow="Compare" title="The ultimate longevity powerhouse." /><div style={{ overflowX: 'auto', border: '1px solid var(--timeline-colors-blackAlpha-200)', borderRadius: 'var(--timeline-radii-lg)' }}><table style={{ width: '100%', minWidth: 720, borderCollapse: 'collapse', textAlign: 'left' }}><thead><tr>{['Comparison criteria', 'Mitopure', 'NAD+', 'CoQ10', 'Creatine'].map(item => <th key={item} style={{ padding: 18, background: sand, fontWeight: 500 }}>{item}</th>)}</tr></thead><tbody>{[['Directly activates mitophagy', 'Yes', 'Partial', 'No', 'No'], ['Targets a root cause of cellular energy decline', 'Yes', 'Partial', 'Partial', 'No'], ['Benefits without changing exercise routine', 'Yes', 'No', 'No', 'No'], ['Human clinical trials', '25+', 'Limited', 'Limited', 'Limited']].map(row => <tr key={row[0]}>{row.map((cell, index) => <td key={cell} style={{ padding: 18, borderTop: '1px solid var(--timeline-colors-blackAlpha-200)', color: index === 1 ? coral : ink }}>{cell}</td>)}</tr>)}</tbody></table></div></section>
    <section style={{ marginTop: 96, background: sand, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(32px, 6vw, 72px)' }}><SectionIntro eyebrow="Quality standards" title="Rigorous science needs rigorous standards." /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 14 }}>{[['Clean Label', 'Independent testing for quality and contaminants.'], ['NSF Certified', 'Verified quality standards for performance products.'], ['Safety reviewed', 'Research and documentation designed around safety.']].map(([title, copy]) => <div key={title} style={{ background: cream, padding: 22, borderRadius: 'var(--timeline-radii-base)' }}><h3 style={{ marginTop: 0, fontFamily: 'var(--timeline-fonts-serif)', fontWeight: 400, fontSize: 'var(--timeline-fontSizes-xl)' }}>{title}</h3><p style={{ marginBottom: 0, lineHeight: 1.5 }}>{copy}</p></div>)}</div></section>
    <section style={{ marginTop: 96, background: ink, color: cream, borderRadius: 'var(--timeline-radii-xl)', padding: 'clamp(32px, 6vw, 72px)' }}><p style={{ color: '#e1a39c', fontSize: 'var(--timeline-fontSizes-2xs-mono)', letterSpacing: '.1em', textTransform: 'uppercase' }}>Powered by science</p><h2 style={{ maxWidth: 760, fontFamily: 'var(--timeline-fonts-serif)', fontSize: 'var(--timeline-fontSizes-3xl)', fontWeight: 400 }}>Change how your cells age. Explore science-backed longevity solutions.</h2><ButtonLink to="/shop">Shop supplements</ButtonLink></section>
  </PageShell>
}

export default FullSciencePage
